config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/open', to: 'courses#open'
  get '/close', to: 'courses#close'
  post '/open', to: 'courses#open'
  post '/close', to: 'courses#close'
  get '/add', to:'courses#add'
  post 'add', to:'courses#increase'
  get '/write', to:'grades#write'
  post '/write', to: 'grades#write'
  get '/done', to:'grades#done'
  post 'done', to:'grades#done'
  get 'succ', to:'courses#succ'
  post 'succ', to:'courses#succ'
  get '/browse', to:'grades#browse'
  resources :courses do
    member do
      post :select
      post :quit
    end
    collection do
      get :list
      post :list
      get :studentselected
      get :subcredit
      
    end
  end
  resources :grades do
    member do
      post :score
      post :done
      get :studentsscorelist
    end
    collection do
      get :scorelist
      
    end
  end
end

app/models/grade.rb
class Grade < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
    before_action :teacher_logged_in, only:[:write, :score]
    def scorelist
        @grades = Grade.where(user_id: current_user.id)
    end

    def upload
        puts params[:student_ids]
    end

     #教师录入成绩
    def write
        @courses = Course.where(teacher_id: current_user.id)
    end

    def browse
        @courses = Course.where(teacher_id: current_user.id)
    end
    #单门课程录入成绩按钮
    def score
        @grades =Grade.where(course_id:params[:id]) 
        # @students = User.all(id:@grades.user_id)
    end

    def studentsscorelist
        @grades =Grade.where(course_id:params[:id]) 
    end

    #成绩录入成功
    def done
        @grade =Grade.find_by(id:params[:id]) 
        @grade.update_attributes(grade: params[:grade])
    end

    def update
        @grade=Grade.find_by_id(params[:id])
        if @grade.update_attributes!(:grade => params[:grade][:grade])
          flash={:success => "#{@grade.user.name} #{@grade.course.name}的成绩已成功修改为 #{@grade.grade}"}
        else
          flash={:danger => "上传失败.请重试"}
        end
        # redirect_to grades_path(course_id: params[:course_id]), flash: flash
      end

    # Confirms a teacher logged-in user.
    def teacher_logged_in
        unless teacher_logged_in?
            redirect_to root_url, flash: {danger: '请登录老师'}
        end
    end
end

app/views/grades/browse.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">教授课程列表</h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
            <th>课程名称</th>
            <th>课程编码</th>
            <th>课程属性</th>
            <th>授课方式</th>
            <th>考试方式</th>
            <th>课时/学分</th>
            <th>限选人数</th>
            <th>已选人数</th>
            <th>教室</th>
            <th>星期节次</th>
            <th>授课教师</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            <% @courses.each do |course| %>
                <tr>
                    <td><%=course.name%></td>
                    <td><%=course.course_code%></td>
                    <td><%=course.course_type%></td>
                    <td><%=course.teaching_type%></td>
                    <td><%=course.exam_type%></td>
                    <td><%=course.credit%></td>
                    <td><%=course.limit_num%></td>
                    <td><%=course.student_num%></td>
                    <td><%=course.class_room%></td>
                    <td><%=course.course_week%></td>
                    <td><%=course.teacher.name%></td>
                    <td><%= link_to "查看成绩", studentsscorelist_grade_path(course), method:"get", class: 'btn btn-sm btn-info' %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/grades/done.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">成绩录入成功</h3>
    </div>
</div>

app/views/grades/score.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">选课学生名单</h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
            <th>课程名</th>
            <th>姓名</th>
            <th>学号</th>
            <th>专业</th>
            <th>学院</th>
            <th>成绩</th>
            </tr>
        </thead>
        <tbody>
            <% @grades.each do |grade| %>
                <tr>
                    <td><%=grade.course.name%></td>
                    <td><%=grade.user.name%></td>
                    <td><%=grade.user.id%></td>
                    <td><%=grade.user.major%></td>
                    <td><%=grade.user.department%></td>
                    <%= form_for grade, url: grade_url(id: grade.id, course_id: grade.course.id), method: :patch do |f| %>
                          <td><%= f.text_field :grade %></td>
                          <td><%= f.submit "提交", class: "btn btn-success btn-xs" %></td>
                    <% end %>
                </tr>
            <% end %>
            
        </tbody>
        </table>
    </div>
</div>

app/views/grades/scorelist.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">成绩单</h3>
    </div>
    <div class="panel-body" style="min-height: 450px">
        <% if !@grades.nil? %>
            <table class="table table-hover table-striped">
            <thead class="thead-light" style="font-size:15px;">
                <tr>
                <th>课程名称</th>
                <th>课程编码</th>
                <th>任课教师</th>
                <th>课程属性</th>
                <th>课时/学分</th>
                <th>成绩</th>
                </tr>
            </thead>
            <tbody>
                <% @grades.each do |grade| %>
                    <% if !grade.grade.nil?%>
                        <tr>
                            <td><%=grade.course.name%></td>
                            <td><%=grade.course.course_code%></td>
                            <td><%=grade.course.teacher.name%></td>
                            <td><%=grade.course.course_type%></td>
                            <td><%=grade.course.credit%></td>
                            <td><%=grade.grade%></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
            </table>
        <% else %>
            <center><p>选课记录为空</p></center>
        <% end %>
    </div>
</div>

app/views/grades/studentsscorelist.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">选课学生成绩</h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
            <th>课程名</th>
            <th>姓名</th>
            <th>学号</th>
            <th>专业</th>
            <th>学院</th>
            <th>成绩</th>
            </tr>
        </thead>
        <tbody>
            <% @grades.each do |grade| %>
                <tr>
                    <td><%=grade.course.name%></td>
                    <td><%=grade.user.name%></td>
                    <td><%=grade.user.id%></td>
                    <td><%=grade.user.major%></td>
                    <td><%=grade.user.department%></td>
                    <td><%=grade.grade%></td>
                </tr>
            <% end %>
            
        </tbody>
        </table>
    </div>
</div>

app/views/grades/write.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">教授课程列表</h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
            <th>课程名称</th>
            <th>课程编码</th>
            <th>课程属性</th>
            <th>授课方式</th>
            <th>考试方式</th>
            <th>课时/学分</th>
            <th>限选人数</th>
            <th>已选人数</th>
            <th>教室</th>
            <th>星期节次</th>
            <th>授课教师</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            <% @courses.each do |course| %>
                <tr>
                    <td><%=course.name%></td>
                    <td><%=course.course_code%></td>
                    <td><%=course.course_type%></td>
                    <td><%=course.teaching_type%></td>
                    <td><%=course.exam_type%></td>
                    <td><%=course.credit%></td>
                    <td><%=course.limit_num%></td>
                    <td><%=course.student_num%></td>
                    <td><%=course.class_room%></td>
                    <td><%=course.course_week%></td>
                    <td><%=course.teacher.name%></td>
                    <td><%= link_to "录入成绩", score_grade_path(course), method:"post", class: 'btn btn-sm btn-info', data: { confirm: "确定为#{course.name}录入成绩?" }  %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>