config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/open', to: 'courses#open'
  get '/close', to: 'courses#close'
  post '/open', to: 'courses#open'
  post '/close', to: 'courses#close'
  get '/add', to:'courses#add'
  post 'add', to:'courses#increase'
  get '/write', to:'grades#write'
  post '/write', to: 'grades#write'
  get '/done', to:'grades#done'
  post 'done', to:'grades#done'
  get 'succ', to:'courses#succ'
  post 'succ', to:'courses#succ'
  get '/browse', to:'grades#browse'
  resources :courses do
    member do
      post :select
      post :quit
    end
    collection do
      get :list
      post :list
      get :studentselected
      get :subcredit
      
    end
  end
  resources :grades do
    member do
      post :score
      post :done
      get :studentsscorelist
    end
    collection do
      get :scorelist
      
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_sidenav.html.erb
<div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">

        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              课程管理</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              选修课程</a>
        <% end %>

      </h4>
    </div>

    <div id="CourseCollapse" class="panel-collapse collapse <%= "in" if ["courses"].include?(params[:controller]) %>">
      <ul class="list-group">

        <% if teacher_logged_in? %>
            <li class="list-group-item">
              <%= link_to courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已授课程
                  <span class="label label-info pull-right"><%= current_user.teaching_courses.count %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to new_course_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 创建新课程
              <% end %>
            </li>
        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to list_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 选修课程
                  <span class="label label-info pull-right"><%= Course.all.count-current_user.courses.count %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已选课程
                  <span class="label label-info pull-right"><%= current_user.courses.count %></span>
              <% end %>
               </li>
            <li class="list-group-item">
              <%= link_to totalcredit_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 选课学分提示
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to timetable_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 个人课表
              <% end %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              成绩管理</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              所有成绩</a>
        <% end %>
      </h4>
    </div>

    <div id="GradeCollapse" class="panel-collapse collapse <%= "in" if ["grades"].include?(params[:controller]) %>">
      <div class="list-group">

        <% if teacher_logged_in? %>
            <% current_user.teaching_courses.each do |course| %>
                <li class="list-group-item">
                  <%= link_to grades_path(course_id: course.id), :method => :get do %>
                      <span class="glyphicon glyphicon-chevron-right"></span> <%= course.name %>
                      <span class="label label-info pull-right"><%= course.users.length %></span>
                  <% end %>
                </li>
            <% end %>

        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to grades_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 所有成绩
              <% end %>
            </li>
        <% end %>

      </div>
    </div>
  </div>
  

  
  <% if student_logged_in? %>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h4 class="panel-title">
        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#EvaluationCollapse"><span class="glyphicon glyphicon-list-alt"></span>
              课程评估</a>
        <% end %>
      </h4>
    </div>
    
    <div id="EvaluationCollapse" class="panel-collapse collapse <%= "in" if request.url.include?"courses/evaluation_index" or 
    (request.url.include?"edit" and request.url.include?"evaluations") %>">

      <ul class="list-group">
        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to evaluation_index_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 当前学期课程评估
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div> 
  <% end %>
  <!--sgg2 end-->

  <!--sgg16-->
  <% if admin_logged_in? %>
  <div class="panel panel-default"> 
    <div class="panel-heading">
      <h4 class="panel-title"> 
        <a data-toggle="collapse" data-parent="#accordion" href="#EvaluationResultsCollapse"><span class="glyphicon glyphicon-list-alt"></span>
        评估管理</a>
      </h4>
    </div>

    <div id="EvaluationResultsCollapse" class="panel-collapse collapse <%= "in" if request.url.include?"evaluations" %>">

      <ul class="list-group">
          <li class="list-group-item">
              <%= link_to evaluations_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 评估结果
              <% end %>
          </li>
          <li class="list-group-item">
              <%= link_to  items_evaluations_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 修改评估项
              <% end %>
          </li>
      </ul>
    </div>

  </div>
  <% end %>
  <!--sgg16 end-->

  <!--sgg21 -->
  <% if teacher_logged_in? %>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h4 class="panel-title">
        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#EvaluationTeacherCollapse"><span class="glyphicon glyphicon-list-alt"></span>
              评估反馈</a>
        <% end %>
      </h4>
    </div>
    
    <div id="EvaluationTeacherCollapse" class="panel-collapse collapse <%= "in" if request.url.include?"feedback" or request.url.include?"result" %>">

      <ul class="list-group">
        <% if teacher_logged_in? %>
            <li class="list-group-item">
              <%= link_to feedback_index_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 课程评估反馈
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div> 
  <% end %>
  
</div>