config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/open', to: 'courses#open'
  get '/close', to: 'courses#close'
  post '/open', to: 'courses#open'
  post '/close', to: 'courses#close'
  get '/add', to:'courses#add'
  post 'add', to:'courses#increase'
  get '/write', to:'grades#write'
  post '/write', to: 'grades#write'
  get '/done', to:'grades#done'
  post 'done', to:'grades#done'
  get 'succ', to:'courses#succ'
  post 'succ', to:'courses#succ'
  get '/browse', to:'grades#browse'
  resources :courses do
    member do
      post :select
      post :quit
    end
    collection do
      get :list
      post :list
      get :studentselected
      get :subcredit
      
    end
  end
  resources :grades do
    member do
      post :score
      post :done
      get :studentsscorelist
    end
    collection do
      get :scorelist
      
    end
  end
end

app/views/layouts/_footer.html.erb
<div class="navbar">
  <footer class="footer container-fluid">
    <p class="text-center">中国科学院大学版权所有 © 2020
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "课程管理", root_path, class: 'navbar-brand' %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "主页", root_path %></li>
        <li><%= link_to "帮助", "https://onestop.ucas.ac.cn/home/tool/f5e477a3-2b5f-495a-8504-86fd91ed12ee/1" %></li>
        <% if logged_in? %>
          <li><%= link_to current_user.name, "" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              账户 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "个人信息", current_user %></li>
              <li><%= link_to "修改信息", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "退出", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "登录", login_path %></li>
          <% end %>

          <% if student_logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              学生平台 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "学期课表", courses_path %></li>
              <li><%= link_to "选修课程", list_courses_path %></li>
              <li><%= link_to "已选课程", studentselected_courses_path %></li>
              <li><%= link_to "成绩查询", scorelist_grades_path %></li>
              <li><%= link_to "查看已选学分", subcredit_courses_path %></li>
            </ul>
          </li>
          <% end %>

          <% if admin_logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              管理员平台 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "开放选课", open_path, method: "post" %></li>
              <li><%= link_to "关闭选课", close_path, method: "post" %></li>
              <li><%= link_to "增加课程", add_path, method: "get" %></li>
            </ul>
          </li>
          <% end %>

           <% if teacher_logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              教师平台 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "录入成绩", write_path, method: "post" %></li>
              <li><%= link_to "查看成绩", browse_path, method: "get" %></li>
            </ul>
          </li>
          <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>国科大课程管理系统</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>